[package]
name = "getting-asynchronous"
version = "0.1.0"
authors = ["Daiki Ihara <sasurau4@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio="0.1"
futures="0.1"
bytes = "0.4"
